# Generated by Django 2.1 on 2019-04-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181112_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('-sort',)},
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
