# Generated by Django 2.1 on 2019-04-18 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190417_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='urlpattern_name',
        ),
        migrations.AddField(
            model_name='page',
            name='card_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='page',
            name='card_link',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='page',
            name='card_source',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='page',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 4, 18)),
        ),
        migrations.AddField(
            model_name='page',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
