# Generated by Django 2.1 on 2019-04-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190418_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_usual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='urlpattern_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='card_description',
            field=models.TextField(blank=True, default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
