# Generated by Django 2.1 on 2019-04-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190418_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='card_link',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='page',
            name='card_source',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='page',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='urlpattern_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
