# Generated by Django 2.1 on 2019-04-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190418_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='urlpattern_name',
            new_name='urlpattern',
        ),
    ]
